FROM arm32v7/openjdk:11-jdk-alpine

ARG SPARK_VERSION=3.0.3
ARG HADOOP_VERSION=3.2

RUN apk add --no-cache bash curl jq

RUN mkdir -p /opt && \
    cd /opt && \
    curl https://archive.apache.org/dist/spark/spark-${SPARK_VERSION}/spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz | tar -zx && \
    mv spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION} spark

ENV SPARK_HOME=/opt/spark

ENV PATH=$PATH:$SPARK_HOME/bin

WORKDIR $SPARK_HOME

CMD ["spark-shell"]
