FROM apache/airflow:2.1.4-python3.8

USER root

RUN apt-get update && \
    apt-get install -y libpq-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN pip install --user 'apache-airflow-providers-postgres==2.0.0'

USER airflow
